src/objects/Testtaker_Test__c.object
<CustomObject>
    <label>Test</label>
    <nameField>
        <label>Test Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Testtaker_Test_Answer__c.object
<CustomObject>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Correct__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Correct?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Test_Question__c</fullName>
        <label>Test Question</label>
        <referenceTo>Testtaker_Test_Question__c</referenceTo>
        <relationshipLabel>Test Answers</relationshipLabel>
        <relationshipName>Test_Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Test Answer</label>
    <nameField>
        <displayFormat>TA-{00000}</displayFormat>
        <label>Test Answer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Testtaker_Test_Question__c.object
<CustomObject>
    <fields>
        <fullName>How_to_Score__c</fullName>
        <label>How to Score</label>
        <picklist>
            <controllingField>Question_Type__c</controllingField>
            <picklistValues>
                <fullName>All or Nothing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allow Partial Scoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Don&apos;t  Score</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Long_Question__c</fullName>
        <description>Full version of the question</description>
        <label>Long Question</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Maximum_Points__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Maximum Points</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Points_Per_Answer__c</fullName>
        <label>Points Per Answer</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <label>Question Type</label>
        <picklist>
            <picklistValues>
                <fullName>Single Select</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Multiple Choice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text Answer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Essay Answer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Short_Question__c</fullName>
        <description>Short version of the question displayed on reports</description>
        <label>Short Question</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Test__c</fullName>
        <label>Test</label>
        <referenceTo>Testtaker_Test__c</referenceTo>
        <relationshipLabel>Test Questions</relationshipLabel>
        <relationshipName>Test_Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Choices__c</fullName>
        <label>Total Choices</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Right_Answers__c</fullName>
        <label>Total Right Answers</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Test Question</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Test Question Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Testtaker_Test_Result__c.object
<CustomObject>
    <description>Contains all the results for a particular test</description>
    <fields>
        <fullName>Completed__c</fullName>
        <label>Completed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Started__c</fullName>
        <description>When the test was initiated</description>
        <label>Started</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Test__c</fullName>
        <label>Test</label>
        <referenceTo>Testtaker_Test__c</referenceTo>
        <relationshipLabel>Test Results</relationshipLabel>
        <relationshipName>Test_Results</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Test Result</label>
    <nameField>
        <displayFormat>TR-{00000}</displayFormat>
        <label>Test Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Testtaker_Test_Result_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Correct_Answer__c</fullName>
        <label>Correct Answer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Max_Score__c</fullName>
        <label>Max Score</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Possible_Answers__c</fullName>
        <description>Possible answers supplied on the test</description>
        <label>Possible Answers</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question_Number__c</fullName>
        <label>Question #</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Recorded_Score__c</fullName>
        <label>Recorded Score</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Supplied_Answer__c</fullName>
        <label>Supplied Answer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Test_Question__c</fullName>
        <label>Test Question</label>
        <referenceTo>Testtaker_Test_Question__c</referenceTo>
        <relationshipLabel>Test Result Details</relationshipLabel>
        <relationshipName>Test_Result_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Test_Result__c</fullName>
        <label>Test Result</label>
        <referenceTo>Testtaker_Test_Result__c</referenceTo>
        <relationshipLabel>Test Result Details</relationshipLabel>
        <relationshipName>Test_Result_Details</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Test Result Detail</label>
    <nameField>
        <displayFormat>TRD-{00000}</displayFormat>
        <label>Detail ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Result Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TT_ReviewTestController.cls
public with sharing class TT_ReviewTestController {
	public TT_ReviewTestController() {
		// use the Instance Id
		testResultId = ApexPages.currentPage().getParameters().get('instanceId');
		
		String questionNumberString = ApexPages.currentPage().getParameters().get('questionNumber');

		system.debug('questionNumberString = ' + questionNumberString);

		
		if(questionNumberString != null){
			questionNumber = Integer.valueOf(questionNumberString);	
		} else {
			questionNumber = 0;
		}
		
		
		system.debug('questionNumber = ' + questionNumber);
		
		testResultQuery = [
			SELECT 
				t.Test__c, t.Started__c, t.Name, t.Id, t.Completed__c 
			FROM 
				Testtaker_Test_Result__c t
			WHERE
				Id=: testResultId	
		];
		
		testId = testResultQuery.Test__c;

		testHeader = [
			SELECT
				Name 
			FROM
				Testtaker_Test__c
			WHERE 
				Id =: testId
		];

		
		allQuestions = [
			SELECT 
				t.Test_Result__c, t.Test_Question__c, t.Supplied_Answer__c, 
				t.Question_Number__c, t.Possible_Answers__c, t.Name, 
				t.Max_Score__c, t.Id, t.Correct_Answer__c 
			FROM 
				Testtaker_Test_Result_Detail__c t
			WHERE 
				t.Test_Result__c =: testResultId 		
			ORDER BY
				Question_Number__c		
		];
		
		if(allQuestions.size() > 0){
			testResultDetailId = allQuestions[questionNumber].Id;
			
			testResultDetail = [
	    		SELECT 
					t.Test_Result__c, t.Test_Question__c, t.Supplied_Answer__c, 
					t.Question_Number__c, t.Possible_Answers__c, t.Name, 
					t.Max_Score__c, t.Id, t.Correct_Answer__c, t.Recorded_Score__c 
				FROM 
					Testtaker_Test_Result_Detail__c t
				WHERE 
					t.Id =: testResultDetailId
	    	];
			
			testAnswer = testResultDetail.Supplied_Answer__c;
			
			testQuestion = [
				SELECT 
					t.Total_Right_Answers__c, t.Total_Choices__c, t.Short_Question__c, 
					t.Question_Type__c, t.Points_Per_Answer__c, t.Name, 
					t.Maximum_Points__c, t.Long_Question__c, t.Id, t.How_to_Score__c 
				FROM 
					Testtaker_Test_Question__c t
				WHERE 
					t.Id =:  testResultDetail.Test_Question__c	
			];
			
			if(testResultDetail.Possible_Answers__c  != ''){
				testAnswers = [
					SELECT 
						t.Test_Question__c, t.Name, t.Is_Correct__c, t.Id, t.Answer__c 
					FROM 
						Testtaker_Test_Answer__c t
					WHERE 
						t.Test_Question__c =: testQuestion.Id	
				];
			}
			
			List<String> correctTestAnswerArray = new List<String>();
			if(testResultDetail.Correct_Answer__c != null){
				correctTestAnswerArray = testResultDetail.Correct_Answer__c.split(',');
			}

			correctTestAnswers = [
				SELECT 
					t.Test_Question__c, t.Name, t.Is_Correct__c, t.Id, t.Answer__c 
				FROM 
					Testtaker_Test_Answer__c t
				WHERE 
					t.Id IN : correctTestAnswerArray

			];

		}		
	}

    public List<SelectOption> getTestAnswerItems() {
        List<SelectOption> options = new List<SelectOption>();
        for (Testtaker_Test_Answer__c t : testAnswers){
        	options.add(new SelectOption(t.Id,t.Answer__c));
        }
        return options;
    }

	public Boolean getCanCompleteTest(){
		return questionNumber == (allQuestions.size() - 1);
	}

	public Boolean getHasNextQuestion(){
		return questionNumber < (allQuestions.size() - 1);
	}

	public Boolean getHasPreviousQuestion(){
		return questionNumber > 0;
	}

	public PageReference submitTestForGrading(){
    	PageReference homePagePage = new PageReference('/apex/TT_ViewResults?instanceID=' + testResultId);
    	homePagePage.setRedirect(true);
    	return homePagePage;
	}


	public PageReference goToNextPage(){
    	PageReference reviewTestPage = new PageReference('/apex/TT_ReviewTest?instanceID=' + testResultId + '&questionNumber=' + String.valueOf(questionNumber + 1));
    	reviewTestPage.setRedirect(true);
    	return reviewTestPage;
	}

	public PageReference goToPreviousPage(){
    	PageReference reviewTestPage = new PageReference('/apex/TT_ReviewTest?instanceID=' + testResultId + '&questionNumber=' + String.valueOf(questionNumber - 1));
    	reviewTestPage.setRedirect(true);
    	return reviewTestPage;
	}

	private void gradeQuestion(){
		Boolean anyErrors = false;
	
	}

	private List<Testtaker_Test_Result_Detail__c> allQuestions;
	private Testtaker_Test_Result__c testResultQuery{get; set;}
    private Id testId{get; set;}
    private Id testResultId{get; set;}
    private Id testResultDetailId{get; set;}    
	private Integer questionNumber{get; set;}
	public String testAnswer{get; set;}

	String[] testAnswerArray =  new String[]{};
	List<Testtaker_Test_Answer__c> correctTestAnswers =  new List<Testtaker_Test_Answer__c>();


    public Testtaker_Test_Question__c testQuestion{get;private set;}
    public Testtaker_Test_Result_Detail__c testResultDetail{get;private set;}
    public List<Testtaker_Test_Answer__c> testAnswers{get;private set;}
	public Testtaker_Test__c testHeader{get;private set;}

	public String[] getTestAnswerArray(){
		if(this.testAnswer != '' && this.testAnswer !=null){
			testAnswerArray = this.testAnswer.split(',');		
		} 
		else {
			testAnswerArray = new List<String>();	
		}
		
		return testAnswerArray;
		// return this.testAnswer.split(',');
	}

	public List<Testtaker_Test_Answer__c> getCorrectTestAnswers(){
		
		return correctTestAnswers;
		// return this.testAnswer.split(',');
	}

	public void setTestAnswerArray(String[] testAnswerArray){
	}



}