src/objects/Testtaker_Test_Answer__c.object
<CustomObject>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Correct__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Correct?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Test_Question__c</fullName>
        <label>Test Question</label>
        <referenceTo>Testtaker_Test_Question__c</referenceTo>
        <relationshipLabel>Test Answers</relationshipLabel>
        <relationshipName>Test_Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Test Answer</label>
    <nameField>
        <displayFormat>TA-{00000}</displayFormat>
        <label>Test Answer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Testtaker_Test_Question__c.object
<CustomObject>
    <fields>
        <fullName>How_to_Score__c</fullName>
        <label>How to Score</label>
        <picklist>
            <controllingField>Question_Type__c</controllingField>
            <picklistValues>
                <fullName>All or Nothing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allow Partial Scoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Don&apos;t  Score</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Long_Question__c</fullName>
        <description>Full version of the question</description>
        <label>Long Question</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Maximum_Points__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Maximum Points</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Points_Per_Answer__c</fullName>
        <label>Points Per Answer</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <label>Question Type</label>
        <picklist>
            <picklistValues>
                <fullName>Single Select</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Multiple Choice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text Answer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Essay Answer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Short_Question__c</fullName>
        <description>Short version of the question displayed on reports</description>
        <label>Short Question</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Test__c</fullName>
        <label>Test</label>
        <referenceTo>Testtaker_Test__c</referenceTo>
        <relationshipLabel>Test Questions</relationshipLabel>
        <relationshipName>Test_Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Choices__c</fullName>
        <label>Total Choices</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Right_Answers__c</fullName>
        <label>Total Right Answers</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Test Question</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Test Question Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Testtaker_Test_Result__c.object
<CustomObject>
    <description>Contains all the results for a particular test</description>
    <fields>
        <fullName>Completed__c</fullName>
        <label>Completed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Started__c</fullName>
        <description>When the test was initiated</description>
        <label>Started</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Test__c</fullName>
        <label>Test</label>
        <referenceTo>Testtaker_Test__c</referenceTo>
        <relationshipLabel>Test Results</relationshipLabel>
        <relationshipName>Test_Results</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Test Result</label>
    <nameField>
        <displayFormat>TR-{00000}</displayFormat>
        <label>Test Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Testtaker_Test_Result_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Correct_Answer__c</fullName>
        <label>Correct Answer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Max_Score__c</fullName>
        <label>Max Score</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Possible_Answers__c</fullName>
        <description>Possible answers supplied on the test</description>
        <label>Possible Answers</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question_Number__c</fullName>
        <label>Question #</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Recorded_Score__c</fullName>
        <label>Recorded Score</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Supplied_Answer__c</fullName>
        <label>Supplied Answer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Test_Question__c</fullName>
        <label>Test Question</label>
        <referenceTo>Testtaker_Test_Question__c</referenceTo>
        <relationshipLabel>Test Result Details</relationshipLabel>
        <relationshipName>Test_Result_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Test_Result__c</fullName>
        <label>Test Result</label>
        <referenceTo>Testtaker_Test_Result__c</referenceTo>
        <relationshipLabel>Test Result Details</relationshipLabel>
        <relationshipName>Test_Result_Details</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Test Result Detail</label>
    <nameField>
        <displayFormat>TRD-{00000}</displayFormat>
        <label>Detail ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Result Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TT_ViewResultsController.cls
public with sharing class TT_ViewResultsController {
	public TT_ViewResultsController() {
		testResultId = ApexPages.currentPage().getParameters().get('instanceId');

		testResultQuery = [
			SELECT 
				t.Test__c, t.Started__c, t.Name, t.Id, t.Completed__c 
			FROM 
				Testtaker_Test_Result__c t
			WHERE
				Id=: testResultId	
		];
		
		testId = testResultQuery.Test__c;
		
		allTestResultDetails = [
			SELECT 
				t.Test_Result__c, t.Test_Question__c, 
				t.Test_Question__r.Name, t.Test_Question__r.Short_Question__c, t.Supplied_Answer__c, 
				t.Question_Number__c, t.Possible_Answers__c, t.Name, 
				t.Max_Score__c, t.Id, t.Correct_Answer__c, t.Recorded_Score__c  
			FROM 
				Testtaker_Test_Result_Detail__c t
			WHERE 
				t.Test_Result__c =: testResultId 		
			ORDER BY
				Question_Number__c		
		];

		allTestQuestions = [
			SELECT 
				t.Total_Right_Answers__c, t.Total_Choices__c, t.Test__c, t.Short_Question__c, 
				t.Question_Type__c, t.Points_Per_Answer__c, t.Name, t.Maximum_Points__c, 
				t.Long_Question__c, t.Id, t.How_to_Score__c 
			FROM 
				Testtaker_Test_Question__c t
			WHERE
				t.Test__c =: testResultQuery.Test__c
		];
		
		allTestAnswers = [
			SELECT 
				t.Test_Question__c, t.Name, t.Is_Correct__c, t.Id, t.Answer__c 
			FROM 
				Testtaker_Test_Answer__c t
			WHERE 
				t.Test_Question__r.Test__c =: testResultQuery.Test__c	
		];


		maximumTestPoints = 0;
		recordedTestPoints = 0;
		finalTestScore = 0;
		// finalTestScore.setScale(2);

		for(Testtaker_Test_Result_Detail__c testResultDetail : allTestResultDetails){
			if(testResultDetail.Max_Score__c != null){
				maximumTestPoints += testResultDetail.Max_Score__c;
			}
			if(testResultDetail.Recorded_Score__c != null){
				recordedTestPoints += testResultDetail.Recorded_Score__c;
			}
			
		}

		if(maximumTestPoints > 0){
			finalTestScore = (recordedTestPoints/maximumTestPoints) * 100;
		}

	}

	public PageReference deleteTest(){
		delete testResultQuery;
    	PageReference homePage = new PageReference('/apex/TT_HomePage');
    	homePage.setRedirect(true);
    	return homePage;		
	}

    public PageReference viewTestResult(){
    	// This function will resume an existing test depending on the id that is passed in

    	PageReference viewResultPage = Page.TT_ReviewTest;
    	viewResultPage.getParameters().put('instanceId',testResultId);
    	return viewResultPage;
    }


    // public Id resultId{get; set;}

	private Id testResultId{get; set;}

	private Testtaker_Test_Result__c testResultQuery{get; set;}
	public List<Testtaker_Test_Result_Detail__c> allTestResultDetails{get;private set;}

    private Id testId{get; set;}
    private Id testResultDetailId{get; set;}    

    public List<Testtaker_Test_Question__c> allTestQuestions{get;private set;}
    public List<Testtaker_Test_Answer__c> allTestAnswers{get;private set;}

    public Decimal maximumTestPoints{get;set;} 
    public Decimal recordedTestPoints{get;set;} 
    public Decimal finalTestScore{get;set;} 


}